spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/sloppyTalk
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 100

logging:
  level:
    org.hibernate.sql: trace
#    root: debug
#    com.toro : debug
server:
  address: 192.168.45.55
  port: 8080



